menu:
  Home: /
  Archives: /archives
  Github: https://github.com/saravanaj
  Twitter: https://twitter.com/saravanaj1
  Feed: /atom.xml

widgets:
- search
- tag
- recent_posts

excerpt_link: Read More

twitter:
  username: saravanaj1
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: false

fancybox: false

google_analytics:
rss:

comment_provider: 
